---
- hosts: ubuntu
  remote_user: flavio
  become: yes
  tasks:
  - name: "Executa o container Mariadb"
    docker_container:
      name: mariadb
      image: mariadb
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      env:
        MYSQL_ROOT_PASSWORD=senha123
        MYSQL_DATABASE=nextcloud
        MYSQL_USER=nextcloud
  - name: "Executa o container nextcloud"
    docker_container:
      name: nextcloud
      image: nextcloud
      ports:
        - 8080:80
      links:
        - mariadb
      volumes:
        - nextcloud:/var/www/html
